AddCSLuaFile()

ENT.Voices = {
	["Flood_Human"] = {
["OnIdle"] = { "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle1.ogg", "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle2.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_noncombat.idle2.ogg", "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle3.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_noncombat.idle4.ogg", "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle5.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/flood/leap.leap1.ogg", "halo_reach/dialog/combat/flood/leap.leap11.ogg",
			"halo_reach/dialog/combat/flood/leap.leap15.ogg", "halo_reach/dialog/combat/flood/leap.leap2.ogg",
			"halo_reach/dialog/combat/flood/leap.leap5.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/flood/flood_idle_combat.melee1.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee10.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee11.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee15.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee2.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee20.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee5.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee6.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee7.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee8.ogg" },
["OnMeleeSFX"] = { "halo_reach/characters/flood/flood_combat_human/stand_pistol_melee/stand_pistol_melee.ogg", "halo_reach/characters/flood/flood_combat_human/stand_pistol_leap_melee/stand_pistol_leap_melee.ogg", "halo_reach/characters/flood/flood_combat_human/stand_pistol_airborne_melee/stand_pistol_airborne_melee.ogg" },
["OnMeleeImpactSFX"] = { "halo_reach/materials/organic_flesh/melee_impact/goopunch.ogg", "halo_reach/materials/organic_flesh/melee_impact/meleehit2.ogg",
			"halo_reach/materials/organic_flesh/melee_impact/meleehit3.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/flood/death.death10.ogg", "halo_reach/dialog/combat/flood/death.death15.ogg",
			"halo_reach/dialog/combat/flood/death.death2.ogg", "halo_reach/dialog/combat/flood/death.death20.ogg",
			"halo_reach/dialog/combat/flood/death.death3.ogg", "halo_reach/dialog/combat/flood/death.death4.ogg",
			"halo_reach/dialog/combat/flood/death.death5.ogg", "halo_reach/dialog/combat/flood/death.ogg" },
["OnLeap"] = { "halo_reach/dialog/combat/flood/flood_idle_combat.leap1.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.leap15.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.leap2.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.leap5.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/flood/pain.pain1.ogg", "halo_reach/dialog/combat/flood/pain.pain15.ogg",
			"halo_reach/dialog/combat/flood/pain.pain2.ogg", "halo_reach/dialog/combat/flood/pain.pain3.ogg",
			"halo_reach/dialog/combat/flood/pain.pain5.ogg", "halo_reach/dialog/combat/flood/pain.pain6.ogg" },
["OnStep"] = { "halo_reach/characters/flood/combat/standpistolmovefront1/standpistolmovefront1.ogg", "halo_reach/characters/flood/combat/standpistolmovefront2/standpistolmovefront2.ogg" },
["OnLand"] = { "halo_reach/characters/footsteps/flood/mud/jump/jump1.ogg", "halo_reach/characters/footsteps/flood/mud/jump/jump3.ogg",
			"halo_reach/characters/footsteps/flood/mud/jump/jump4.ogg" },
["OnJump"] = { "halo_reach/characters/footsteps/flood/mud/jump_up/jump1.ogg", "halo_reach/characters/footsteps/flood/mud/jump_up/jump5.ogg" }
	},
	["Flood_Elite"] = {
["OnIdle"] = { "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle1.ogg", "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle2.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_noncombat.idle2.ogg", "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle3.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_noncombat.idle4.ogg", "halo_reach/dialog/combat/flood/flood_idle_noncombat.idle5.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/flood/leap.leap1.ogg", "halo_reach/dialog/combat/flood/leap.leap11.ogg",
			"halo_reach/dialog/combat/flood/leap.leap15.ogg", "halo_reach/dialog/combat/flood/leap.leap2.ogg",
			"halo_reach/dialog/combat/flood/leap.leap5.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/flood/flood_idle_combat.melee1.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee10.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee11.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee15.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee2.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee20.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee5.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee6.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.melee7.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.melee8.ogg" },
["OnMeleeSFX"] = { "halo_reach/characters/flood/flood_combat_elite/stand_pistol_melee_2/stand_pistol_melee_2.ogg", "halo_reach/characters/flood/flood_combat_elite/stand_pistol_melee_airborne/stand_pistol_melee_airborne.ogg", "halo_reach/characters/flood/flood_combat_elite/stand_pistol_leap_melee/stand_pistol_leap_melee.ogg" },
["OnMeleeImpactSFX"] = { "halo_reach/materials/organic_flesh/melee_impact/goopunch.ogg", "halo_reach/materials/organic_flesh/melee_impact/meleehit2.ogg",
			"halo_reach/materials/organic_flesh/melee_impact/meleehit3.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/flood/death.death10.ogg", "halo_reach/dialog/combat/flood/death.death15.ogg",
			"halo_reach/dialog/combat/flood/death.death2.ogg", "halo_reach/dialog/combat/flood/death.death20.ogg",
			"halo_reach/dialog/combat/flood/death.death3.ogg", "halo_reach/dialog/combat/flood/death.death4.ogg",
			"halo_reach/dialog/combat/flood/death.death5.ogg", "halo_reach/dialog/combat/flood/death.ogg" },
["OnLeap"] = { "halo_reach/dialog/combat/flood/flood_idle_combat.leap1.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.leap15.ogg",
			"halo_reach/dialog/combat/flood/flood_idle_combat.leap2.ogg", "halo_reach/dialog/combat/flood/flood_idle_combat.leap5.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/flood/pain.pain1.ogg", "halo_reach/dialog/combat/flood/pain.pain15.ogg",
			"halo_reach/dialog/combat/flood/pain.pain2.ogg", "halo_reach/dialog/combat/flood/pain.pain3.ogg",
			"halo_reach/dialog/combat/flood/pain.pain5.ogg", "halo_reach/dialog/combat/flood/pain.pain6.ogg" },
["OnStep"] = { "halo_reach/characters/flood/combat/standpistolmovefront1/standpistolmovefront1.ogg", "halo_reach/characters/flood/combat/standpistolmovefront2/standpistolmovefront2.ogg" },
["OnLand"] = { "halo_reach/characters/footsteps/flood/mud/jump/jump1.ogg", "halo_reach/characters/footsteps/flood/mud/jump/jump3.ogg",
			"halo_reach/characters/footsteps/flood/mud/jump/jump4.ogg" },
["OnJump"] = { "halo_reach/characters/footsteps/flood/mud/jump_up/jump1.ogg", "halo_reach/characters/footsteps/flood/mud/jump_up/jump5.ogg" }
	}
}