AddCSLuaFile()

ENT.Voices = {
	["Skirmisher"] = {
["OnIdle"] = { "halo_reach/dialog/combat/jackal_skirmisher/idle/answer_06.ogg", "halo_reach/dialog/combat/jackal_skirmisher/idle/answer_10.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/idle/answer_15.ogg", "halo_reach/dialog/combat/jackal_skirmisher/idle/answer_41.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/idle/answer_48.ogg", "halo_reach/dialog/combat/jackal_skirmisher/idle/foundfoe_11.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/idle/invsgt_04.ogg", "halo_reach/dialog/combat/jackal_skirmisher/idle/invsgt_23.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_04.ogg", "halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_05.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_10.ogg", "halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_15.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/seefoe/dwn_16.ogg" },
["OnSurprise"] = { "halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_05.ogg", "halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_05.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/srprs/bump_07.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/jackal_skirmisher/invsgt/invsgt_05.ogg", "halo_reach/dialog/combat/jackal_skirmisher/invsgt/invsgt_06.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/invsgt/invsgt_06.ogg", "halo_reach/dialog/combat/jackal_skirmisher/invsgt/invsgt_08.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/invsgt/invsgt_09.ogg", "halo_reach/dialog/combat/jackal_skirmisher/invsgt/invsgt_10.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_07.ogg", "halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_08.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_09.ogg", "halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_10.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_11.ogg", "halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_12.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_13.ogg", "halo_reach/dialog/combat/jackal_skirmisher/lst_cntct/hrdfoe_old_14.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/jackal_skirmisher/shoot/pain_mjr_06.ogg", "halo_reach/dialog/combat/jackal_skirmisher/shoot/pain_mjr_12.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/shoot/pain_mjr_18.ogg", "halo_reach/dialog/combat/jackal_skirmisher/shoot/pain_mjr_25.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/shoot/prst_07.ogg", "halo_reach/dialog/combat/jackal_skirmisher/shoot/prst_11.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/shoot/prst_11.ogg", "halo_reach/dialog/combat/jackal_skirmisher/shoot/scld_09.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/shoot/scld_10.ogg" },
["OnDamagedFoe"] = { "halo_reach/dialog/combat/jackal_skirmisher/damaged_enemy/prst_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/damaged_enemy/prst_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/damaged_enemy/prst_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/damaged_enemy/prst_09.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/damaged_enemy/prst_13.ogg", "halo_reach/dialog/combat/jackal_skirmisher/damaged_enemy/prst_17.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/jackal_skirmisher/thrtn/curse_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/thrtn/curse_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/thrtn/curse_05.ogg", "halo_reach/dialog/combat/jackal_skirmisher/thrtn/curse_06.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/thrtn/curse_09.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/jackal_skirmisher/chr/chr_04.ogg", "halo_reach/dialog/combat/jackal_skirmisher/chr/chr_16.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/chr/chr_17.ogg", "halo_reach/dialog/combat/jackal_skirmisher/chr/chr_18.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/chr/chr_19.ogg", "halo_reach/dialog/combat/jackal_skirmisher/chr/chr_20.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/chr/chr_23.ogg" },
["OnUnderAttack"] = { "halo_reach/dialog/combat/jackal_skirmisher/undr_fire/strk_33.ogg", "halo_reach/dialog/combat/jackal_skirmisher/undr_fire/taunt_06.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/undr_fire/thrtn_04.ogg", "halo_reach/dialog/combat/jackal_skirmisher/undr_fire/thrtn_05.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/undr_fire/thrtn_07.ogg", "halo_reach/dialog/combat/jackal_skirmisher/undr_fire/thrtn_08.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/jackal_skirmisher/warn/strk_21.ogg", "halo_reach/dialog/combat/jackal_skirmisher/warn/strk_22.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/warn/strk_25.ogg", "halo_reach/dialog/combat/jackal_skirmisher/warn/strk_35.ogg", 
			"halo_reach/dialog/combat/jackal_skirmisher/warn/taunt_02.ogg", "halo_reach/dialog/combat/jackal_skirmisher/warn/warn_1.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/jackal_skirmisher/dive/dive_1.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dive/dive_2.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dive/dive_3.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dive/dive_4.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dive/dive_5.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dive/dive_7.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dive/dive_8.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_1.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_2.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_3.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_4.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_5.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_6.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dodge/dodge_7.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_05.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_06.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_07.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_08.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_09.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_10.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_11.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_12.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_13.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_14.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/dth_15.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth/dth_16.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth/pain_mjr_27.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_08.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_09.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_10.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_11.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_12.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_13.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth_mjr/dth_fall_14.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_05.ogg", "halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_06.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/dth_fall/dth_fall_07.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/jackal_skirmisher/thrwn/thrwn_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/thrwn/thrwn_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/thrwn/thrwn_07.ogg", "halo_reach/dialog/combat/jackal_skirmisher/thrwn/thrwn_11.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/thrwn/thrwn_12.ogg", "halo_reach/dialog/combat/jackal_skirmisher/thrwn/thrwn_14.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/jackal_skirmisher/fall/fall_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/fall/fall_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/fall/fall_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/fall/fall_04.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_01.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_02.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/pain/pain_03.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/pain/pain_05.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_06.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/pain/pain_07.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_08.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/pain/pain_09.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_10.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/pain/pain_11.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain/pain_13.ogg" },
["OnStep"] = { "halo_reach/characters/jackal/shortmove/shortmove1.ogg", "halo_reach/characters/jackal/shortmove/shortmove2.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove3.ogg", "halo_reach/characters/jackal/shortmove/shortmove4.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove5.ogg", "halo_reach/characters/jackal/shortmove/shortmove6.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove7.ogg", "halo_reach/characters/jackal/shortmove/shortmove8.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove9.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/jackal_skirmisher/pain_mjr/pain_mjr_02.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain_mjr/pain_mjr_04.ogg",
			"halo_reach/dialog/combat/jackal_skirmisher/pain_mjr/pain_mjr_16.ogg", "halo_reach/dialog/combat/jackal_skirmisher/pain_mjr/pain_mjr_26.ogg" }
	}
}