AddCSLuaFile()

ENT.Voices = {
	["Elite"] = {
		["OnIdle"] = { "halo_reach/dialog/combat/elite1/08_idle/idle/idle_10.ogg", "halo_reach/dialog/combat/elite1/08_idle/idle/idle_11.ogg",
			"halo_reach/dialog/combat/elite1/08_idle/idle/idle_12.ogg", "halo_reach/dialog/combat/elite1/08_idle/idle/idle_2.ogg",
			"halo_reach/dialog/combat/elite1/08_idle/idle/idle_3.ogg", "halo_reach/dialog/combat/elite1/08_idle/idle/idle_4.ogg",
			"halo_reach/dialog/combat/elite1/08_idle/idle/idle_7.ogg", "halo_reach/dialog/combat/elite1/08_idle/idle/idle_8.ogg",
			"halo_reach/dialog/combat/elite1/08_idle/idle/searching_1.ogg", "halo_reach/dialog/combat/elite1/08_idle/idle/searching_16.ogg",
			"halo_reach/dialog/combat/elite1/08_idle/idle/searching_17.ogg", "halo_reach/dialog/combat/elite1/08_idle/idle/searching_2.ogg",
			"halo_reach/dialog/combat/elite1/08_idle/idle/searching_3.ogg" },
		["OnAlert"] = { "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_1.ogg", "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_10.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_11.ogg", "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_13.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_14.ogg", "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_2.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_3.ogg", "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_4.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_5.ogg", "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_6.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_7.ogg", "halo_reach/dialog/combat/elite1/01_contact/seefoe/seefoe_8.ogg" },
		["OnAlertMoreFoes"] = { "halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_1.ogg", "halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_10.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_11.ogg", "halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_2.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_4.ogg", "halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_7.ogg",
			"halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_8.ogg", "halo_reach/dialog/combat/elite1/01_contact/morefoe/morefoe_9.ogg" },
		["OnInvestigate"] = { "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_1.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_10.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_11.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_12.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_13.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_2.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_3.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_4.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_5.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_7.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_8.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt/invsgt_9.ogg" },
		["OnInvestigateFail"] = { "halo_reach/dialog/combat/elite1/05_search/invsgt_fail/invsgt_fail_1.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt_fail/invsgt_fail_2.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt_fail/invsgt_fail_3.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt_fail/invsgt_fail_4.ogg",
			"halo_reach/dialog/combat/elite1/05_search/invsgt_fail/invsgt_fail_5.ogg", "halo_reach/dialog/combat/elite1/05_search/invsgt_fail/invsgt_fail_6.ogg" },
		["OnLostContact"] = { "halo_reach/dialog/combat/elite1/05_search/lst_cntct/lst_cntct_2.ogg", "halo_reach/dialog/combat/elite1/05_search/lst_cntct/lst_cntct_3.ogg",
			"halo_reach/dialog/combat/elite1/05_search/lst_cntct/lst_cntct_4.ogg", "halo_reach/dialog/combat/elite1/05_search/lst_cntct/lst_cntct_5.ogg" },
		["OnAttack"] = { "halo_reach/dialog/combat/elite1/02_combat/strk/strk_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_10.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_13.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_15.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_16.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_17.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_18.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_19.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_2.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_20.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_21.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_22.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_23.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_24.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_4.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk/strk_7.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk/strk_8.ogg" },
		["OnBerserk"] = { "halo_reach/dialog/combat/elite1/02_combat/brsrk/brsrk_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/brsrk/brsrk_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/brsrk/brsrk_5.ogg", "halo_reach/dialog/combat/elite1/02_combat/brsrk/brsrk_6.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/brsrk/charge_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/brsrk/charge_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/brsrk/charge_4.ogg" },
		["OnCharge"] = { "halo_reach/dialog/combat/elite1/02_combat/charge/charge_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/charge/charge_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/charge/charge_4.ogg", "halo_reach/dialog/combat/elite1/02_combat/charge/charge_5.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/charge/charge_6.ogg", "halo_reach/dialog/combat/elite1/02_combat/charge/charge_7.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/charge/charge_8.ogg", "halo_reach/dialog/combat/elite1/02_combat/charge/charge_9.ogg" },
		["OnDamagedFoe"] = { "halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_10.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_12.ogg", "halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_3.ogg", "halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_4.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_5.ogg", "halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_6.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_7.ogg", "halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_8.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/damaged_enemy/damaged_enemy_9.ogg" },
		["OnCover"] = { "halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_10.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_12.ogg", "halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_12.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_12.ogg", "halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_6.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_8.ogg", "halo_reach/dialog/combat/elite1/02_combat/move_cvr/move_cvr_9.ogg" },
		["OnReload"] = { "halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_3.ogg", "halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_4.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_5.ogg", "halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_7.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/reloading/reloading_8.ogg" },
		["OnGrenadeThrow"] = { "halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_10.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_11.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_14.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_3.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_5.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_6.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_7.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_8.ogg", "halo_reach/dialog/combat/elite1/02_combat/strk_grnd/strk_grnd_9.ogg" },
		["OnTaunt"] = { "halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_10.ogg", "halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_11.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_16.ogg", "halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_17.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_18.ogg", "halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_3.ogg", "halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_4.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_7.ogg", "halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_8.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/thrtn/thrtn_9.ogg" },
		["OnVictory"] = { "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_1.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_10.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_11.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_13.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_14.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_15.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_16.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_2.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_3.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_5.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_6.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_7.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_8.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr/chr_9.ogg" },
		["OnKillPlayer"] = { "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_10.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_12.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_13.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_15.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_17.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_19.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_2.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_21.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_23.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_3.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_5.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_6.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_7.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_8.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/chr_deadmc/chr_deadmc_9.ogg" },
		["OnPanic"] = { "halo_reach/dialog/combat/elite1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_1.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_2.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_3.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_4.ogg",
			"halo_reach/dialog/combat/elite1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_6.ogg", "halo_reach/dialog/combat/elite1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_7.ogg" },
		["OnUnderAttack"] = { "halo_reach/dialog/combat/elite1/02_combat/undr_fire/undr_fire_2.ogg", "halo_reach/dialog/combat/elite1/02_combat/undr_fire/undr_fire_3.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/undr_fire/undr_fire_4.ogg", "halo_reach/dialog/combat/elite1/02_combat/undr_fire/undr_fire_5.ogg", 
			"halo_reach/dialog/combat/elite1/02_combat/undr_fire/undr_fire_6.ogg", "halo_reach/dialog/combat/elite1/02_combat/undr_fire/undr_fire_7.ogg" },
		["OnWarnIncoming"] = { "halo_reach/dialog/combat/elite1/02_combat/warn_incmn/warn_incmn_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/warn_incmn/warn_incmn_2.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/warn_incmn/warn_incmn_3.ogg", "halo_reach/dialog/combat/elite1/02_combat/warn_incmn/warn_incmn_4.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/warn_incmn/warn_incmn_5.ogg", "halo_reach/dialog/combat/elite1/02_combat/warn_incmn/warn_incmn_6.ogg" },
		["OnMelee"] = { "halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_1.ogg", "halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_10.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_2.ogg", "halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_3.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_4.ogg", "halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_4.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_6.ogg", "halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_7.ogg",
			"halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_8.ogg", "halo_reach/dialog/combat/elite1/02_combat/melee_attack/melee_attack_9.ogg" },
		["OnDive"] = { "halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_11.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_12.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_2.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_3.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_4.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_5.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_6.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_7.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_8.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dive/dive_9.ogg"},
		["OnDodge"] = { "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_10.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_11.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_13.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_14.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_2.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_3.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_3.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_5.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_6.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_7.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_8.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dodge/dodge_9.ogg" },
		["OnDeath"] = { "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_11.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_12.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_14.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_15.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_16.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_17.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_2.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_3.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_4.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_5.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_6.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth/dth_7.ogg" },
		["OnDeathPainful"] = { "halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_11.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_13.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_14.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_15.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_2.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_4.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_5.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_6.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_7.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_mjr/dth_mjr_9.ogg" },
		["OnFallDeath"] = { "halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_2.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_3.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_4.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_6.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_7.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/dth_fall/dth_fall_9.ogg" },
		["OnDeathThrown"] = { "halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_11.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_12.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_13.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_3.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_5.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_6.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_7.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_8.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/thrwn/thrwn_9.ogg" },
		["OnFall"] = { "halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_10.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_2.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_3.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_4.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_5.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_7.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/fall/fall_9.ogg" },
		["OnHurt"] = { "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_2.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_3.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_4.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_5.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_6.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/pain_shld_8.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_1.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_11.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_14.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_2.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_22.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_23.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_25.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_27.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_3.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_4.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_5.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_6.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_shld/small_pain_9.ogg" },
		["OnHurtLarge"] = { "halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_1.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_11.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_12.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_13.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_14.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_3.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_5.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_6.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_7.ogg", "halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_8.ogg",
			"halo_reach/dialog/combat/elite1/11_involuntary/pain_mjr/pain_mjr_9.ogg" },
		["OnStep"] = { "halo_reach/characters/footsteps/elite/stone/run/stone_run1.ogg", "halo_reach/characters/footsteps/elite/stone/run/stone_run2.ogg",
			"halo_reach/characters/footsteps/elite/stone/run/stone_run3.ogg", "halo_reach/characters/footsteps/elite/stone/run/stone_run4.ogg",
			"halo_reach/characters/footsteps/elite/stone/run/stone_run5.ogg", "halo_reach/characters/footsteps/elite/stone/run/stone_run6.ogg" },
		["OnLand"] = { "halo_reach/characters/footsteps/elite/stone/jump_land/stone_land1.ogg", "halo_reach/characters/footsteps/elite/stone/jump_land/stone_land2.ogg",
			"halo_reach/characters/footsteps/elite/stone/jump_land/stone_land3.ogg", "halo_reach/characters/footsteps/elite/stone/jump_land/stone_land4.ogg",
			"halo_reach/characters/footsteps/elite/stone/jump_land/stone_land5.ogg", "halo_reach/characters/footsteps/elite/stone/jump_land/stone_land6.ogg" },
		["OnShieldPop"] = { "halo_reach/characters/spartan/shield_pop_spartan/shield_pop_spartan1.ogg", "halo_reach/characters/spartan/shield_pop_spartan/shield_pop_spartan2.ogg",
			"halo_reach/characters/spartan/shield_pop_spartan/shield_pop_spartan3.ogg" }
	},
	["Brute"] = {
["OnIdle"] = { "halo_reach/dialog/combat/brute1/08_idle/idle/idle_1.ogg", "halo_reach/dialog/combat/brute1/08_idle/idle/idle_11.ogg",
		"halo_reach/dialog/combat/brute1/08_idle/idle/idle_12.ogg", "halo_reach/dialog/combat/brute1/08_idle/idle/idle_13.ogg",
		"halo_reach/dialog/combat/brute1/08_idle/idle/idle_14.ogg", "halo_reach/dialog/combat/brute1/08_idle/idle/idle_2.ogg",
		"halo_reach/dialog/combat/brute1/08_idle/idle/idle_3.ogg", "halo_reach/dialog/combat/brute1/08_idle/idle/idle_4.ogg",
		"halo_reach/dialog/combat/brute1/08_idle/idle/idle_7.ogg", "halo_reach/dialog/combat/brute1/08_idle/idle/idle_9.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_1.ogg", "halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_10.ogg",
		"halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_11.ogg", "halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_2.ogg",
		"halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_3.ogg", "halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_4.ogg",
		"halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_5.ogg", "halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_6.ogg",
		"halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_7.ogg", "halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_8.ogg",
		"halo_reach/dialog/combat/brute1/01_contact/seefoe/seefoe_9.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_1.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_3.ogg",
		"halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_4.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_5.ogg",
		"halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_6.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_7.ogg",
		"halo_reach/dialog/combat/brute1/05_search/invsgt/invsgt_9.ogg" },
["OnInvestigateFail"] = { "halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_1.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_10.ogg",
		"halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_2.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_5.ogg",
		"halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_6.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_7.ogg",
		"halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_8.ogg", "halo_reach/dialog/combat/brute1/05_search/invsgt_fail/invsgt_fail_9.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/brute1/05_search/lst_cntct/lst_cntct_1.ogg", "halo_reach/dialog/combat/brute1/05_search/lst_cntct/lst_cntct_2.ogg",
		"halo_reach/dialog/combat/brute1/05_search/lst_cntct/lst_cntct_3.ogg", "halo_reach/dialog/combat/brute1/05_search/lst_cntct/lst_cntct_4.ogg",
		"halo_reach/dialog/combat/brute1/05_search/lst_cntct/lst_cntct_5.ogg", "halo_reach/dialog/combat/brute1/05_search/lst_cntct/lst_cntct_6.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/brute1/02_combat/strk/strk_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_10.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_12.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_13.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_14.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_15.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_15.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_17.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_18.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_19.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_20.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_21.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_22.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_23.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_24.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_3.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_4.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_5.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_6.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk/strk_7.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk/strk_8.ogg" },
["OnBerserk"] = { "halo_reach/dialog/combat/brute1/02_combat/brsrk/brsrk_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/brsrk/brsrk_2.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/brsrk/charge_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/brsrk/charge_2.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/brsrk/charge_3.ogg", "halo_reach/dialog/combat/brute1/02_combat/brsrk/charge_4.ogg" },
["OnCharge"] = { "halo_reach/dialog/combat/brute1/02_combat/charge/charge_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/charge/charge_2.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/charge/charge_3.ogg", "halo_reach/dialog/combat/brute1/02_combat/charge/charge_4.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/charge/charge_5.ogg", "halo_reach/dialog/combat/brute1/02_combat/charge/charge_5.ogg" },
["OnDamagedFoe"] = { "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_10.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_11.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_12.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_13.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_14.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_15.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_16.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_17.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_18.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_2.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_3.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_4.ogg", "halo_reach/dialog/combat/brute1/02_combat/damaged_enemy/damaged_enemy_7.ogg" },
["OnFlee"] = { "halo_reach/dialog/combat/brute1/02_combat/flee/flee_2.ogg", "halo_reach/dialog/combat/brute1/02_combat/flee/flee_3.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/flee/flee_4.ogg", "halo_reach/dialog/combat/brute1/02_combat/flee/flee_5.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/flee/flee_6.ogg", "halo_reach/dialog/combat/brute1/02_combat/flee/flee_7.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/flee/flee_8.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_2.ogg", "halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_3.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_4.ogg", "halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_4.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_6.ogg", "halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_6.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/melee_attack/melee_attack_8.ogg" },
["OnCover"] = { "halo_reach/dialog/combat/brute1/02_combat/move_cvr/move_cvr_2.ogg", "halo_reach/dialog/combat/brute1/02_combat/move_cvr/move_cvr_4.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/move_cvr/move_cvr_5.ogg", "halo_reach/dialog/combat/brute1/02_combat/move_cvr/move_cvr_6.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/move_cvr/move_cvr_7.ogg", "halo_reach/dialog/combat/brute1/02_combat/move_cvr/move_cvr_8.ogg" },
["OnReload"] = { "halo_reach/dialog/combat/brute1/02_combat/reloading/reloading_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/reloading/reloading_2.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/reloading/reloading_3.ogg", "halo_reach/dialog/combat/brute1/02_combat/reloading/reloading_5.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/reloading/reloading_6.ogg" },
["OnGrenadeThrow"] = { "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_10.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_11.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_12.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_13.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_14.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_15.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_16.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_17.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_18.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_2.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_3.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_4.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_5.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_7.ogg", "halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_8.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/strk_grnd/strk_grnd_9.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_10.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_11.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_12.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_13.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_14.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_15.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_16.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_17.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_18.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_2.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_3.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_4.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_5.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_6.ogg", "halo_reach/dialog/combat/brute1/02_combat/thrtn/thrtn_8.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_1.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_10.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_11.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_2.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_3.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_4.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_5.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_6.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_7.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_8.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr/chr_9.ogg" },
["OnKillPlayer"] = { "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_10.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_12.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_14.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_15.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_16.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_17.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_18.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_5.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_6.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_7.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_8.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/chr_deadmc/chr_deadmc_9.ogg" },
["OnPanic"] = { "halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_1.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_2.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_3.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_4.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_5.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_6.ogg",
		"halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_7.ogg", "halo_reach/dialog/combat/brute1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_8.ogg" 	},
["OnUnderAttack"] = { "halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_10.ogg", "halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_2.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_3.ogg", "halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_4.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_5.ogg", "halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_6.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_7.ogg", "halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_8.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/undr_fire/undr_fire_9.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_1.ogg", "halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_2.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_3.ogg", "halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_4.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_5.ogg", "halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_6.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_7.ogg", "halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_8.ogg",
		"halo_reach/dialog/combat/brute1/02_combat/warn_incmn/warn_incmn_9.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_2.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_3.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_4.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_5.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_6.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_7.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_8.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dive/dive_9.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_2.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_3.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_4.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_5.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_6.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_7.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_8.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dodge/dodge_9.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_10.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_11.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_12.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_13.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_14.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_15.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_16.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_17.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_2.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_3.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_4.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_5.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_6.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_7.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_8.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth/dth_9.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_10.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_11.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_12.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_2.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_3.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_4.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_5.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_6.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_7.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_8.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_mjr/dth_mjr_9.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_10.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_11.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_12.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_2.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_3.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_4.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_5.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_6.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_7.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_8.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/dth_fall/dth_fall_9.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_2.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_3.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_4.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_4.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_6.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_7.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_8.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/thrwn/thrwn_9.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_10.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_2.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_3.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_4.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_5.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_6.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_7.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_8.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/fall/fall_9.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_10.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_11.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_12.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_13.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_14.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_15.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_16.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_17.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_2.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_3.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_4.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_5.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_6.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_7.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_8.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain/pain_9.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_1.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_10.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_11.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_2.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_3.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_4.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_5.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_6.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_7.ogg", "halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_8.ogg",
		"halo_reach/dialog/combat/brute1/11_involuntary/pain_mjr/pain_mjr_9.ogg"},
["OnStep"] = { "halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run1.ogg", "halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run13.ogg",
		"halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run2.ogg", "halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run21.ogg",
		"halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run23.ogg", "halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run24.ogg",
		"halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run3.ogg", "halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run4.ogg",
		"halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run6.ogg", "halo_reach/characters/footsteps/brute/grtcement/run/grtcem_run8.ogg" },
["SFXOnMelee"] = { "halo_reach/characters/brute/brute_board_hits/brute_hit1.ogg", "halo_reach/characters/brute/brute_board_hits/brute_hit2.ogg",
		"halo_reach/characters/brute/brute_board_hits/brute_hit3.ogg", "halo_reach/characters/brute/brute_board_hits/brute_hit4.ogg",
		"halo_reach/characters/brute/brute_board_hits/brute_hit5.ogg", "halo_reach/characters/brute/brute_board_hits/brute_hit6.ogg" }
	}
}