AddCSLuaFile()
 
ENT.Voices = {
	["Hunter"] = {
["OnAlert"] = { "halo_reach/dialog/combat/hunter/seefoe/dth_reanimated8.ogg", "halo_reach/dialog/combat/hunter/seefoe/dwn18.ogg",
			"halo_reach/dialog/combat/hunter/seefoe/dwn3.ogg", "halo_reach/dialog/combat/hunter/seefoe/melee6.ogg",
			"halo_reach/dialog/combat/hunter/seefoe/thrwn1.ogg", "halo_reach/dialog/combat/hunter/seefoe/warn51.ogg",
			"halo_reach/dialog/combat/hunter/seefoe/warn52.ogg", "halo_reach/dialog/combat/hunter/seefoe/warn53.ogg",
			"halo_reach/dialog/combat/hunter/seefoe/warn54.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/hunter/invsgt/dwn10.ogg", "halo_reach/dialog/combat/hunter/invsgt/dwn13.ogg",
			"halo_reach/dialog/combat/hunter/invsgt/dwn14.ogg", "halo_reach/dialog/combat/hunter/invsgt/dwn8.ogg",
			"halo_reach/dialog/combat/hunter/invsgt/dwn9.ogg", "halo_reach/dialog/combat/hunter/invsgt/warn38.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/hunter/lst_cntct/dwn1.ogg", "halo_reach/dialog/combat/hunter/lst_cntct/dwn15.ogg",
			"halo_reach/dialog/combat/hunter/lst_cntct/dwn16.ogg", "halo_reach/dialog/combat/hunter/lst_cntct/dwn19.ogg",
			"halo_reach/dialog/combat/hunter/lst_cntct/dwn2.ogg", "halo_reach/dialog/combat/hunter/lst_cntct/dwn2.ogg",
			"halo_reach/dialog/combat/hunter/lst_cntct/dwn21.ogg", "halo_reach/dialog/combat/hunter/lst_cntct/dwn21.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/hunter/strk/dth_mjr10.ogg", "halo_reach/dialog/combat/hunter/strk/flee1.ogg",
			"halo_reach/dialog/combat/hunter/strk/flee1.ogg", "halo_reach/dialog/combat/hunter/strk/pain_shld12.ogg",
			"halo_reach/dialog/combat/hunter/strk/reanimate13.ogg", "halo_reach/dialog/combat/hunter/strk/reanimate15.ogg",
			"halo_reach/dialog/combat/hunter/strk/stun14.ogg", "halo_reach/dialog/combat/hunter/strk/stun9.ogg" },
["OnBerserk"] = { "halo_reach/dialog/combat/hunter/brsrk/charge13.ogg", "halo_reach/dialog/combat/hunter/brsrk/dth_hdsht17.ogg",
			"halo_reach/dialog/combat/hunter/brsrk/dth_mjr14.ogg", "halo_reach/dialog/combat/hunter/brsrk/dth_mjr18.ogg",
			"halo_reach/dialog/combat/hunter/brsrk/dth_mjr24.ogg", "halo_reach/dialog/combat/hunter/brsrk/dth_mjr25.ogg",
			"halo_reach/dialog/combat/hunter/brsrk/kamikaze1.ogg", "halo_reach/dialog/combat/hunter/brsrk/reanimate16.ogg",
			"halo_reach/dialog/combat/hunter/brsrk/reanimate16.ogg" },
["OnCharge"] = { "halo_reach/dialog/combat/hunter/charge/charge1.ogg", "halo_reach/dialog/combat/hunter/charge/charge14.ogg",
			"halo_reach/dialog/combat/hunter/charge/charge2.ogg", "halo_reach/dialog/combat/hunter/charge/charge4.ogg",
			"halo_reach/dialog/combat/hunter/charge/charge7.ogg", "halo_reach/dialog/combat/hunter/charge/dth_mjr21.ogg",
			"halo_reach/dialog/combat/hunter/charge/dth_mjr23.ogg", "halo_reach/dialog/combat/hunter/charge/fall12.oggg",
			"halo_reach/dialog/combat/hunter/charge/fall6.ogg", "halo_reach/dialog/combat/hunter/charge/fall6.ogg",
			"halo_reach/dialog/combat/hunter/charge/reanimate12.ogg", "halo_reach/dialog/combat/hunter/charge/thrwn12.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/hunter/thrtn/charge3.ogg", "halo_reach/dialog/combat/hunter/thrtn/charge5.ogg",
			"halo_reach/dialog/combat/hunter/thrtn/charge6.ogg", "halo_reach/dialog/combat/hunter/thrtn/charge8.ogg",
			"halo_reach/dialog/combat/hunter/thrtn/melee13.ogg", "halo_reach/dialog/combat/hunter/thrtn/meleeleap11.ogg",
			"halo_reach/dialog/combat/hunter/thrtn/meleeleap13.ogg", "halo_reach/dialog/combat/hunter/thrtn/meleeleap14.ogg",
			"halo_reach/dialog/combat/hunter/thrtn/reanimate14.ogg", "halo_reach/dialog/combat/hunter/thrtn/thrwn14.ogg",
			"halo_reach/dialog/combat/hunter/thrtn/thrwn15.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/hunter/chr/1.ogg", "halo_reach/dialog/combat/hunter/chr/2.ogg",
			"halo_reach/dialog/combat/hunter/chr/3.ogg", "halo_reach/dialog/combat/hunter/chr/4.ogg",
			"halo_reach/dialog/combat/hunter/chr/5.ogg", "halo_reach/dialog/combat/hunter/chr/6.ogg",
			"halo_reach/dialog/combat/hunter/chr/7.ogg", "halo_reach/dialog/combat/hunter/chr/8.ogg",
			"halo_reach/dialog/combat/hunter/chr/9.ogg", "halo_reach/dialog/combat/hunter/chr/melee9.ogg",
			"halo_reach/dialog/combat/hunter/chr/melee9.ogg", "halo_reach/dialog/combat/hunter/chr/melee9.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/hunter/warn/warn17.ogg", "halo_reach/dialog/combat/hunter/warn/warn18.ogg",
			"halo_reach/dialog/combat/hunter/warn/warn25.ogg", "halo_reach/dialog/combat/hunter/warn/warn26.ogg",
			"halo_reach/dialog/combat/hunter/warn/warn27.ogg", "halo_reach/dialog/combat/hunter/warn/warn29.ogg",
			"halo_reach/dialog/combat/hunter/warn/warn32.ogg", "halo_reach/dialog/combat/hunter/warn/warn33.ogg",
			"halo_reach/dialog/combat/hunter/warn/warn35.ogg", "halo_reach/dialog/combat/hunter/warn/warn36.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/hunter/melee/10.ogg", "halo_reach/dialog/combat/hunter/melee/15.ogg",
			"halo_reach/dialog/combat/hunter/melee/3.ogg", "halo_reach/dialog/combat/hunter/melee/4.ogg",
			"halo_reach/dialog/combat/hunter/melee/7.ogg", "halo_reach/dialog/combat/hunter/melee/8.ogg",
			"halo_reach/dialog/combat/hunter/melee/8.ogg", "halo_reach/dialog/combat/hunter/melee/9.ogg",
			"halo_reach/dialog/combat/hunter/melee/melee1.ogg", "halo_reach/dialog/combat/hunter/melee/melee10.ogg",
			"halo_reach/dialog/combat/hunter/melee/melee11.ogg", "halo_reach/dialog/combat/hunter/melee/melee12.ogg",
			"halo_reach/dialog/combat/hunter/melee/melee14.ogg", "halo_reach/dialog/combat/hunter/melee/melee15.ogg",
			"halo_reach/dialog/combat/hunter/melee/melee16.ogg", "halo_reach/dialog/combat/hunter/melee/melee2.ogg",
			"halo_reach/dialog/combat/hunter/melee/melee3.ogg", "halo_reach/dialog/combat/hunter/melee/melee8.ogg",
			"halo_reach/dialog/combat/hunter/melee/meleeleap2.ogg", "halo_reach/dialog/combat/hunter/melee/meleeleap3.ogg",
			"halo_reach/dialog/combat/hunter/melee/meleeleap4.ogg", "halo_reach/dialog/combat/hunter/melee/meleeleap6.ogg",
			"halo_reach/dialog/combat/hunter/melee/meleeleap9.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/hunter/dive/dth_hdsht11.ogg", "halo_reach/dialog/combat/hunter/dive/dth_hdsht13.ogg",
			"halo_reach/dialog/combat/hunter/dive/dth_mjr26.ogg", "halo_reach/dialog/combat/hunter/dive/dth_mjr4.ogg",
			"halo_reach/dialog/combat/hunter/dive/lift5.ogg", "halo_reach/dialog/combat/hunter/dive/lift7.ogg",
			"halo_reach/dialog/combat/hunter/dive/lift8.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/hunter/dodge/dth_hdsht9.ogg", "halo_reach/dialog/combat/hunter/dodge/dth_mjr19.ogg",
			"halo_reach/dialog/combat/hunter/dodge/dth_mjr19.ogg", "halo_reach/dialog/combat/hunter/dodge/dth_mjr2.ogg",
			"halo_reach/dialog/combat/hunter/dodge/dth_mjr9.ogg", "halo_reach/dialog/combat/hunter/dodge/dwn5.ogg",
			"halo_reach/dialog/combat/hunter/dodge/lift3.ogg", "halo_reach/dialog/combat/hunter/dodge/lift6.ogg",
			"halo_reach/dialog/combat/hunter/dodge/lift9.ogg", "halo_reach/dialog/combat/hunter/dodge/meleeleap10.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/hunter/dth/dth11.ogg", "halo_reach/dialog/combat/hunter/dth/dth12.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth14.ogg", "halo_reach/dialog/combat/hunter/dth/dth15.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth3.ogg", "halo_reach/dialog/combat/hunter/dth/dth5.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth6.ogg", "halo_reach/dialog/combat/hunter/dth/dth7.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth8.ogg", "halo_reach/dialog/combat/hunter/dth/dth_drama4.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth_slnt1.ogg", "halo_reach/dialog/combat/hunter/dth/dth_slnt3.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth_slnt4.ogg", "halo_reach/dialog/combat/hunter/dth/dth_slnt5.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth_slnt6.ogg", "halo_reach/dialog/combat/hunter/dth/dth_slnt7.ogg",
			"halo_reach/dialog/combat/hunter/dth/dth_slnt8.ogg", "halo_reach/dialog/combat/hunter/dth/dth_slw8.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/hunter/dth_mjr/charge10.ogg", "halo_reach/dialog/combat/hunter/dth_mjr/charge11.ogg",
			"halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr1.ogg", "halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr12.ogg",
			"halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr13.ogg", "halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr22.ogg",
			"halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr3.ogg", "halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr5.ogg",
			"halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr6.ogg", "halo_reach/dialog/combat/hunter/dth_mjr/dth_mjr8.ogg",
			"halo_reach/dialog/combat/hunter/dth_mjr/dth_slnt2.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/hunter/dth_fall/dth_fall1.ogg", "halo_reach/dialog/combat/hunter/dth_fall/dth_fall2.ogg",
			"halo_reach/dialog/combat/hunter/dth_fall/dth_fall3.ogg", "halo_reach/dialog/combat/hunter/dth_fall/dth_fall4.ogg",
			"halo_reach/dialog/combat/hunter/dth_fall/dth_fall5.ogg", "halo_reach/dialog/combat/hunter/dth_fall/dth_fall6.ogg",
			"halo_reach/dialog/combat/hunter/dth_fall/dth_fall7.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/hunter/thrwn/dth_slw5.ogg", "halo_reach/dialog/combat/hunter/thrwn/thrwn11.ogg",
			"halo_reach/dialog/combat/hunter/thrwn/thrwn13.ogg", "halo_reach/dialog/combat/hunter/thrwn/thrwn16.ogg",
			"halo_reach/dialog/combat/hunter/thrwn/thrwn2.ogg", "halo_reach/dialog/combat/hunter/thrwn/thrwn3.ogg",
			"halo_reach/dialog/combat/hunter/thrwn/thrwn4.ogg", "halo_reach/dialog/combat/hunter/thrwn/thrwn5.ogg",
			"halo_reach/dialog/combat/hunter/thrwn/thrwn6.ogg", "halo_reach/dialog/combat/hunter/thrwn/thrwn7.ogg",
			"halo_reach/dialog/combat/hunter/thrwn/thrwn8.ogg", "halo_reach/dialog/combat/hunter/thrwn/thrwn9.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/hunter/fall/charge12.ogg", "halo_reach/dialog/combat/hunter/fall/dth_slw12.ogg",
			"halo_reach/dialog/combat/hunter/fall/fall2.ogg", "halo_reach/dialog/combat/hunter/fall/fall4.ogg",
			"halo_reach/dialog/combat/hunter/fall/fall5.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/hunter/pain/16.ogg", "halo_reach/dialog/combat/hunter/pain/dth1.ogg",
			"halo_reach/dialog/combat/hunter/pain/dth13.ogg", "halo_reach/dialog/combat/hunter/pain/dth2.ogg",
			"halo_reach/dialog/combat/hunter/pain/dth_mjr11.ogg", "halo_reach/dialog/combat/hunter/pain/dth_mjr20.ogg",
			"halo_reach/dialog/combat/hunter/pain/lift1.ogg", "halo_reach/dialog/combat/hunter/pain/lift2.ogg",
			"halo_reach/dialog/combat/hunter/pain/meleeleap1.ogg", "halo_reach/dialog/combat/hunter/pain/meleeleap12.ogg",
			"halo_reach/dialog/combat/hunter/pain/pain1.ogg", "halo_reach/dialog/combat/hunter/pain/pain2.ogg",
			"halo_reach/dialog/combat/hunter/pain/pain4.ogg", "halo_reach/dialog/combat/hunter/pain/pain5.ogg",
			"halo_reach/dialog/combat/hunter/pain/pain7.ogg", "halo_reach/dialog/combat/hunter/pain/pain8.ogg",
			"halo_reach/dialog/combat/hunter/pain/pain9.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/hunter/pain_mjr/dth_hdsht15.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/dth_mjr15.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/dth_mjr16.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/dth_mjr17.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/dth_reanimated1.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/dth_reanimated2.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/dth_reanimated3.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/dth_reanimated4.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/dth_reanimated6.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/dth_reanimated6.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/dth_slw2.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/dth_slw2.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/meleeleap5.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/meleeleap5.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/pain_mjr3.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/pain_mjr4.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/pain_mjr6.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/pain_mjr7.ogg",
			"halo_reach/dialog/combat/hunter/pain_mjr/pain_mjr9.ogg", "halo_reach/dialog/combat/hunter/pain_mjr/reanimate10.ogg" },
["OnStep"] = { "halo_reach/characters/hunter/land_soft/land_soft_1.ogg", "halo_reach/characters/hunter/land_soft/land_soft_2.ogg",
			"halo_reach/characters/hunter/land_soft/land_soft_3.ogg", "halo_reach/characters/hunter/land_soft/land_soft_4.ogg",
			"halo_reach/characters/hunter/land_soft/land_soft_4.ogg", "halo_reach/characters/hunter/land_soft/land_soft_6.ogg",
			"halo_reach/characters/hunter/land_soft/land_soft_7.ogg" },
["OnLand"] = { "halo_reach/characters/hunter/land_hard/land_1.ogg", "halo_reach/characters/hunter/land_hard/land_2.ogg",
			"halo_reach/characters/hunter/land_hard/land_3.ogg", "halo_reach/characters/hunter/land_hard/land_4.ogg",
			"halo_reach/characters/hunter/land_hard/land_5.ogg", "halo_reach/characters/hunter/land_hard/land_6.ogg",
			"halo_reach/characters/hunter/land_hard/land_7.ogg" },
["SFXOnMeleeBack"] = { "halo_reach/characters/hunter/melee_back/melee_back_1.ogg", "halo_reach/characters/hunter/melee_back/melee_back_2.ogg",
			"halo_reach/characters/hunter/melee_back/melee_back_3.ogg" },
["SFXOnMelee"] = { "halo_reach/characters/hunter/melee_var1/melee_var1_1.ogg", "halo_reach/characters/hunter/melee_var1/melee_var1_2.ogg",
			"halo_reach/characters/hunter/melee_var1/melee_var1_3.ogg", "halo_reach/characters/hunter/melee_var2/melee_var2_1.ogg",
			"halo_reach/characters/hunter/melee_var2/melee_var2_2.ogg", "halo_reach/characters/hunter/melee_var2/melee_var2_3.ogg",
			"halo_reach/characters/hunter/melee_var3/melee_var3_1.ogg", "halo_reach/characters/hunter/melee_var3/melee_var3_2.ogg",
			"halo_reach/characters/hunter/melee_var3/melee_var3_3.ogg", "halo_reach/characters/hunter/melee_var4/melee_var4_1.ogg",
			"halo_reach/characters/hunter/melee_var4/melee_var4_2.ogg", "halo_reach/characters/hunter/melee_var4/melee_var4_3.ogg" },
["SFXOnMeleeLeft"] = { "halo_reach/characters/hunter/smash_left/smash_left_1.ogg", "halo_reach/characters/hunter/smash_left/smash_right_2.ogg",
			"halo_reach/characters/hunter/smash_left/smash_right_3.ogg" },
["SFXOnMeleeRight"] = { "halo_reach/characters/hunter/smash_right/smash_right_1.ogg", "halo_reach/characters/hunter/smash_right/smash_right_2.ogg",
			"halo_reach/characters/hunter/smash_right/smash_right_3.ogg" },
["SFXOnMeleeHitBiped"] = { "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage1.ogg", "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage2.ogg",
			"halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage3.ogg", "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage4.ogg",
			"halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage5.ogg", "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage6.ogg" },
["SFXOnMeleeHitWorld"] = { "halo_reach/characters/hunter/hunter_melee_hits/hunter_melee_hit1.ogg", "halo_reach/characters/hunter/hunter_melee_hits/hunter_melee_hit2.ogg",
			"halo_reach/characters/hunter/hunter_melee_hits/hunter_melee_hit3.ogg", "halo_reach/characters/hunter/hunter_melee_hits/hunter_melee_hit4.ogg",
			"halo_reach/characters/hunter/hunter_melee_hits/hunter_melee_hit5.ogg", "halo_reach/characters/hunter/hunter_melee_hits/hunter_melee_hit6.ogg" },
["SFXOnMeleeSwing"] = { "halo_reach/characters/hunter/hunter_arm_melee/hunter_arm_melee1.ogg", "halo_reach/characters/hunter/hunter_arm_melee/hunter_arm_melee2.ogg",
			"halo_reach/characters/hunter/hunter_arm_melee/hunter_arm_melee3.ogg" },
["SFXOnBeamCharge"] = { "halo_reach/weapons/hunter_cannon/hunter_charge.ogg" },
["SFXOnBeamFire"] = { "halo_reach/weapons/hunter_cannon/hunter_cannon_loop/hunter_cannon/in.ogg" }
	}
}