AddCSLuaFile()

ENT.Voices = {
	["Jackal"] = {
["OnIdle"] = { "halo_reach/dialog/combat/jackal/idle/hrdfoe_idle1.ogg", "halo_reach/dialog/combat/jackal/idle/hrdfoe_idle2.ogg",
			"halo_reach/dialog/combat/jackal/idle/hrdfoe_idle3.ogg", "halo_reach/dialog/combat/jackal/idle/hrdfoe_idle4.ogg",
			"halo_reach/dialog/combat/jackal/idle/hrdfoe_idle5.ogg", "halo_reach/dialog/combat/jackal/idle/hrdfoe_idle6.ogg",
			"halo_reach/dialog/combat/jackal/idle/hrdfoe_idle7.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/jackal/seefoe/seefoe1.ogg", "halo_reach/dialog/combat/jackal/seefoe/seefoe2.ogg",
			"halo_reach/dialog/combat/jackal/seefoe/seefoe3.ogg", "halo_reach/dialog/combat/jackal/seefoe/seefoe4.ogg",
			"halo_reach/dialog/combat/jackal/seefoe/seefoe5.ogg", "halo_reach/dialog/combat/jackal/seefoe/seefoe6.ogg",
			"halo_reach/dialog/combat/jackal/seefoe/seefoe7.ogg", "halo_reach/dialog/combat/jackal/seefoe/seefoe8.ogg",
			"halo_reach/dialog/combat/jackal/seefoe/seefoe9.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/jackal/invsgt/invsgt1.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt2.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt3.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt4.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt5.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt6.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt7.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt9.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt10.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt11.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt12.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt13.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt14.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt15.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt16.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt17.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt18.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt19.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt20.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt21.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt22.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt23.ogg",
			"halo_reach/dialog/combat/jackal/invsgt/invsgt24.ogg", "halo_reach/dialog/combat/jackal/invsgt/invsgt25.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/jackal/lst_cntct/chirp1.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp10.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/chirp11.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp12.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/chirp13.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp14.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/chirp2.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp3.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/chirp4.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp5.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/chirp6.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp7.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/chirp8.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/chirp9.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct22.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct23.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct24.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct25.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct26.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct27.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct28.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct29.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct30.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct31.ogg",
			"halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct32.ogg", "halo_reach/dialog/combat/jackal/lst_cntct/lst_cntct33.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/jackal/shoot/hrdfoe_old16.ogg", "halo_reach/dialog/combat/jackal/shoot/hrdfoe_old17.ogg",
			"halo_reach/dialog/combat/jackal/shoot/hrdfoe_old18.ogg", "halo_reach/dialog/combat/jackal/shoot/hrdfoe_old19.ogg",
			"halo_reach/dialog/combat/jackal/shoot/hrdfoe_old20.ogg", "halo_reach/dialog/combat/jackal/shoot/hrdfoe_old21.ogg",
			"halo_reach/dialog/combat/jackal/shoot/hrdfoe_old22.ogg", "halo_reach/dialog/combat/jackal/shoot/hrdfoe_old23.ogg" },
["OnShield"] = { "halo_reach/dialog/combat/jackal/stayback/stayback1.ogg", "halo_reach/dialog/combat/jackal/stayback/stayback10.ogg",
			"halo_reach/dialog/combat/jackal/stayback/stayback11.ogg", "halo_reach/dialog/combat/jackal/stayback/stayback12.ogg",
			"halo_reach/dialog/combat/jackal/stayback/stayback13.ogg", "halo_reach/dialog/combat/jackal/stayback/stayback2.ogg",
			"halo_reach/dialog/combat/jackal/stayback/stayback3.ogg", "halo_reach/dialog/combat/jackal/stayback/stayback4.ogg",
			"halo_reach/dialog/combat/jackal/stayback/stayback5.ogg", "halo_reach/dialog/combat/jackal/stayback/stayback6.ogg",
			"halo_reach/dialog/combat/jackal/stayback/stayback7.ogg", "halo_reach/dialog/combat/jackal/stayback/stayback8.ogg",
			"halo_reach/dialog/combat/jackal/stayback/stayback9.ogg" },
["OnCower"] = { "halo_reach/dialog/combat/jackal/whn/whn1.ogg", "halo_reach/dialog/combat/jackal/whn/whn10.ogg",
			"halo_reach/dialog/combat/jackal/whn/whn11.ogg", "halo_reach/dialog/combat/jackal/whn/whn12.ogg",
			"halo_reach/dialog/combat/jackal/whn/whn13.ogg", "halo_reach/dialog/combat/jackal/whn/whn2.ogg",
			"halo_reach/dialog/combat/jackal/whn/whn3.ogg", "halo_reach/dialog/combat/jackal/whn/whn4.ogg",
			"halo_reach/dialog/combat/jackal/whn/whn5.ogg", "halo_reach/dialog/combat/jackal/whn/whn6.ogg",
			"halo_reach/dialog/combat/jackal/whn/whn7.ogg", "halo_reach/dialog/combat/jackal/whn/whn8.ogg",
			"halo_reach/dialog/combat/jackal/whn/whn9.ogg" },
["OnFlee"] = { "halo_reach/dialog/combat/jackal/flee/flee1.ogg", "halo_reach/dialog/combat/jackal/flee/flee2.ogg",
			"halo_reach/dialog/combat/jackal/flee/flee3.ogg", "halo_reach/dialog/combat/jackal/flee/flee4.ogg",
			"halo_reach/dialog/combat/jackal/flee/flee5.ogg", "halo_reach/dialog/combat/jackal/flee/flee6.ogg",
			"halo_reach/dialog/combat/jackal/flee/flee7.ogg", "halo_reach/dialog/combat/jackal/flee/flee8.ogg",
			"halo_reach/dialog/combat/jackal/flee/flee9.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/jackal/thrtn/thrtn10.ogg", "halo_reach/dialog/combat/jackal/thrtn/thrtn11.ogg",
			"halo_reach/dialog/combat/jackal/thrtn/thrtn3.ogg", "halo_reach/dialog/combat/jackal/thrtn/thrtn4.ogg",
			"halo_reach/dialog/combat/jackal/thrtn/thrtn5.ogg", "halo_reach/dialog/combat/jackal/thrtn/thrtn6.ogg",
			"halo_reach/dialog/combat/jackal/thrtn/thrtn7.ogg", "halo_reach/dialog/combat/jackal/thrtn/thrtn8.ogg",
			"halo_reach/dialog/combat/jackal/thrtn/thrtn9.ogg" },
["OnPanic"] = { "halo_reach/dialog/combat/jackal/panic_plsmgrnd/dth_drama2.ogg", "halo_reach/dialog/combat/jackal/panic_plsmgrnd/dth_drama3.ogg",
			"halo_reach/dialog/combat/jackal/panic_plsmgrnd/dth_mjr1.ogg", "halo_reach/dialog/combat/jackal/panic_plsmgrnd/dth_mjr23.ogg",
			"halo_reach/dialog/combat/jackal/panic_plsmgrnd/dth_mjr5.ogg", "halo_reach/dialog/combat/jackal/panic_plsmgrnd/dth_slnt16.ogg" },
["OnUnderAttack"] = { "halo_reach/dialog/combat/jackal/undr_fire/hrdfoe_old24.ogg", "halo_reach/dialog/combat/jackal/undr_fire/hrdfoe_old25.ogg",
			"halo_reach/dialog/combat/jackal/undr_fire/hrdfoe_old25.ogg", "halo_reach/dialog/combat/jackal/undr_fire/hrdfoe_old27.ogg",
			"halo_reach/dialog/combat/jackal/undr_fire/hrdfoe_old28.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/jackal/warn/warn1.ogg", "halo_reach/dialog/combat/jackal/warn/warn2.ogg", 
			"halo_reach/dialog/combat/jackal/warn/warn3.ogg", "halo_reach/dialog/combat/jackal/warn/warn4.ogg",
			"halo_reach/dialog/combat/jackal/warn/warn5.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/jackal/dwn/dwn1.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn10.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn11.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn12.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn13.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn14.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn15.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn16.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn17.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn18.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn19.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn2.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn20.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn21.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn22.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn23.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn24.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn25.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn3.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn4.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn5.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn6.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn7.ogg", "halo_reach/dialog/combat/jackal/dwn/dwn8.ogg",
			"halo_reach/dialog/combat/jackal/dwn/dwn9.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/jackal/dive/dive1.ogg", "halo_reach/dialog/combat/jackal/dive/dive2.ogg",
			"halo_reach/dialog/combat/jackal/dive/dive3.ogg", "halo_reach/dialog/combat/jackal/dive/dive4.ogg",
			"halo_reach/dialog/combat/jackal/dive/dive5.ogg", "halo_reach/dialog/combat/jackal/dive/dive6.ogg",
			"halo_reach/dialog/combat/jackal/dive/dive7.ogg", "halo_reach/dialog/combat/jackal/dive/dive8.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/jackal/dodge/dodge1.ogg", "halo_reach/dialog/combat/jackal/dodge/dodge10.ogg",
			"halo_reach/dialog/combat/jackal/dodge/dodge2.ogg", "halo_reach/dialog/combat/jackal/dodge/dodge3.ogg",
			"halo_reach/dialog/combat/jackal/dodge/dodge4.ogg", "halo_reach/dialog/combat/jackal/dodge/dodge5.ogg",
			"halo_reach/dialog/combat/jackal/dodge/dodge6.ogg", "halo_reach/dialog/combat/jackal/dodge/dodge7.ogg",
			"halo_reach/dialog/combat/jackal/dodge/dodge8.ogg", "halo_reach/dialog/combat/jackal/dodge/dodge9.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/jackal/dth/dth1.ogg", "halo_reach/dialog/combat/jackal/dth/dth10.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth11.ogg", "halo_reach/dialog/combat/jackal/dth/dth12.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth13.ogg", "halo_reach/dialog/combat/jackal/dth/dth14.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth15.ogg", "halo_reach/dialog/combat/jackal/dth/dth2.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth3.ogg", "halo_reach/dialog/combat/jackal/dth/dth4.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth5.ogg", "halo_reach/dialog/combat/jackal/dth/dth6.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth7.ogg", "halo_reach/dialog/combat/jackal/dth/dth8.ogg",
			"halo_reach/dialog/combat/jackal/dth/dth9.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr1.ogg", "halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr2.ogg",
			"halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr23.ogg", "halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr3.ogg",
			"halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr4.ogg", "halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr5.ogg",
			"halo_reach/dialog/combat/jackal/dth_mjr/dth_mjr6.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/jackal/dth_fall/dth_fall1.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall10.ogg",
			"halo_reach/dialog/combat/jackal/dth_fall/dth_fall11.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall12.ogg",
			"halo_reach/dialog/combat/jackal/dth_fall/dth_fall13.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall14.ogg",
			"halo_reach/dialog/combat/jackal/dth_fall/dth_fall2.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall3.ogg",
			"halo_reach/dialog/combat/jackal/dth_fall/dth_fall4.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall5.ogg",
			"halo_reach/dialog/combat/jackal/dth_fall/dth_fall6.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall7.ogg",
			"halo_reach/dialog/combat/jackal/dth_fall/dth_fall8.ogg", "halo_reach/dialog/combat/jackal/dth_fall/dth_fall9.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/jackal/thrwn/thrwn1.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn10.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn11.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn12.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn13.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn14.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn15.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn16.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn2.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn3.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn4.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn5.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn6.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn7.ogg",
			"halo_reach/dialog/combat/jackal/thrwn/thrwn8.ogg", "halo_reach/dialog/combat/jackal/thrwn/thrwn9.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/jackal/fall/fall1.ogg", "halo_reach/dialog/combat/jackal/fall/fall2.ogg",
			"halo_reach/dialog/combat/jackal/fall/fall3.ogg", "halo_reach/dialog/combat/jackal/fall/fall4.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/jackal/pain/pain1.ogg", "halo_reach/dialog/combat/jackal/pain/pain10.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain11.ogg", "halo_reach/dialog/combat/jackal/pain/pain12.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain13.ogg", "halo_reach/dialog/combat/jackal/pain/pain14.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain15.ogg", "halo_reach/dialog/combat/jackal/pain/pain16.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain17.ogg", "halo_reach/dialog/combat/jackal/pain/pain18.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain19.ogg", "halo_reach/dialog/combat/jackal/pain/pain2.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain20.ogg", "halo_reach/dialog/combat/jackal/pain/pain3.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain4.ogg", "halo_reach/dialog/combat/jackal/pain/pain5.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain6.ogg", "halo_reach/dialog/combat/jackal/pain/pain7.ogg",
			"halo_reach/dialog/combat/jackal/pain/pain8.ogg", "halo_reach/dialog/combat/jackal/pain/pain9.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr1.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr10.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr11.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr12.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr13.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr14.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr15.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr2.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr3.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr4.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr5.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr6.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr7.ogg", "halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr8.ogg",
			"halo_reach/dialog/combat/jackal/pain_mjr/pain_mjr9.ogg" },
["OnStep"] = { "halo_reach/characters/jackal/shortmove/shortmove1.ogg", "halo_reach/characters/jackal/shortmove/shortmove1.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove3.ogg", "halo_reach/characters/jackal/shortmove/shortmove4.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove5.ogg", "halo_reach/characters/jackal/shortmove/shortmove6.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove7.ogg", "halo_reach/characters/jackal/shortmove/shortmove8.ogg",
			"halo_reach/characters/jackal/shortmove/shortmove9.ogg" }
			}
}