AddCSLuaFile()

ENT.Voices = {
	["Drone"] = {
["OnIdle"] = { "halo_reach/dialog/combat/bugger/idle/h3_2_27.ogg", "halo_reach/dialog/combat/bugger/idle/h3_2_41.ogg",
			"halo_reach/dialog/combat/bugger/idle/h3_2_5.ogg", "halo_reach/dialog/combat/bugger/idle/h3_3_13.ogg",
			"halo_reach/dialog/combat/bugger/idle/h3_3_31.ogg", "halo_reach/dialog/combat/bugger/idle/h3_4_8.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/bugger/seefoe/h3_1_2.ogg", "halo_reach/dialog/combat/bugger/seefoe/h3_2_19.ogg",
			"halo_reach/dialog/combat/bugger/seefoe/h3_2_2.ogg", "halo_reach/dialog/combat/bugger/seefoe/h3_2_28.ogg",
			"halo_reach/dialog/combat/bugger/seefoe/h3_2_40.ogg", "halo_reach/dialog/combat/bugger/seefoe/h3_3_1.ogg",
			"halo_reach/dialog/combat/bugger/seefoe/h3_3_15.ogg", "halo_reach/dialog/combat/bugger/seefoe/h3_3_24.ogg",
			"halo_reach/dialog/combat/bugger/seefoe/h3_3_36.ogg", "halo_reach/dialog/combat/bugger/seefoe/h3_3_38.ogg",
			"halo_reach/dialog/combat/bugger/seefoe/h3_4_15.ogg", "halo_reach/dialog/combat/bugger/seefoe/h3_4_31.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/bugger/invsgt/h3_2_66.ogg", "halo_reach/dialog/combat/bugger/invsgt/h3_2_67.ogg",
					"halo_reach/dialog/combat/bugger/invsgt/h3_2_69.ogg", "halo_reach/dialog/combat/bugger/invsgt/h3_2_70.ogg",
					"halo_reach/dialog/combat/bugger/invsgt/h3_2_71.ogg", "halo_reach/dialog/combat/bugger/invsgt/h3_2_72.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/bugger/lst_cntct/h3_2_73.ogg", "halo_reach/dialog/combat/bugger/lst_cntct/h3_2_74.ogg",
			"halo_reach/dialog/combat/bugger/lst_cntct/h3_2_75.ogg", "halo_reach/dialog/combat/bugger/lst_cntct/h3_2_76.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/bugger/strk/h3_1_22.ogg", "halo_reach/dialog/combat/bugger/strk/h3_1_23.ogg",
			"halo_reach/dialog/combat/bugger/strk/h3_1_4.ogg", "halo_reach/dialog/combat/bugger/strk/h3_1_6.ogg",
			"halo_reach/dialog/combat/bugger/strk/h3_2_13.ogg", "halo_reach/dialog/combat/bugger/strk/h3_2_17.ogg",
			"halo_reach/dialog/combat/bugger/strk/h3_2_18.ogg", "halo_reach/dialog/combat/bugger/strk/h3_2_24.ogg",
			"halo_reach/dialog/combat/bugger/strk/h3_2_25.ogg", "halo_reach/dialog/combat/bugger/strk/h3_2_33.ogg",
			"halo_reach/dialog/combat/bugger/strk/h3_2_39.ogg", "halo_reach/dialog/combat/bugger/strk/h3_2_49.ogg",
			"halo_reach/dialog/combat/bugger/strk/h3_2_8.ogg" },
["OnDamagedFoe"] = { "halo_reach/dialog/combat/bugger/damaged_enemy/h3_2_47.ogg", "halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_14.ogg",
			"halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_14.ogg", "halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_20.ogg",
			"halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_25.ogg", "halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_37.ogg",
			"halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_5.ogg", "halo_reach/dialog/combat/bugger/damaged_enemy/h3_3_8.ogg",
			"halo_reach/dialog/combat/bugger/damaged_enemy/h3_4_16.ogg", "halo_reach/dialog/combat/bugger/damaged_enemy/h3_4_22.ogg",
			"halo_reach/dialog/combat/bugger/damaged_enemy/h3_4_7.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/bugger/chr/h3_1_29.ogg", "halo_reach/dialog/combat/bugger/chr/h3_2_14.ogg",
			"halo_reach/dialog/combat/bugger/chr/h3_2_4.ogg", "halo_reach/dialog/combat/bugger/chr/h3_2_52.ogg",
			"halo_reach/dialog/combat/bugger/chr/h3_2_53.ogg", "halo_reach/dialog/combat/bugger/chr/h3_2_59.ogg",
			"halo_reach/dialog/combat/bugger/chr/h3_2_63.ogg" },
["OnUnderAttack"] = { "halo_reach/dialog/combat/bugger/undr_fire/h3_1_28.ogg", "halo_reach/dialog/combat/bugger/undr_fire/h3_2_81.ogg",
			"halo_reach/dialog/combat/bugger/undr_fire/h3_2_82.ogg", "halo_reach/dialog/combat/bugger/undr_fire/h3_2_82.ogg",
			"halo_reach/dialog/combat/bugger/undr_fire/h3_3_2.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/bugger/dive/h3_2_1.ogg", "halo_reach/dialog/combat/bugger/dive/h3_2_1.ogg",
			"halo_reach/dialog/combat/bugger/dive/h3_4_11.ogg", "halo_reach/dialog/combat/bugger/dive/h3_4_4.ogg",
			"halo_reach/dialog/combat/bugger/dive/h3_4_5.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/bugger/dodge/h3_1_5.ogg", "halo_reach/dialog/combat/bugger/dodge/h3_2_30.ogg",
			"halo_reach/dialog/combat/bugger/dodge/h3_3_35.ogg", "halo_reach/dialog/combat/bugger/dodge/h3_4_23.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/bugger/dth/h3_1_7.ogg", "halo_reach/dialog/combat/bugger/dth/h3_2_22.ogg", "halo_reach/dialog/combat/bugger/dth/h3_2_55.ogg",
			"halo_reach/dialog/combat/bugger/dth/h3_2_65.ogg", "halo_reach/dialog/combat/bugger/dth/h3_4_10.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/bugger/dth_drama/h3_1_15.ogg", "halo_reach/dialog/combat/bugger/dth_drama/h3_2_68.ogg",
			"halo_reach/dialog/combat/bugger/dth_drama/h3_3_18.ogg", "halo_reach/dialog/combat/bugger/dth_drama/h3_4_20.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/bugger/dth_fall/h3_1_18.ogg", "halo_reach/dialog/combat/bugger/dth_fall/h3_4_30.ogg",
			"halo_reach/dialog/combat/bugger/dth_fall/h3_4_33.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/bugger/thrwn/h3_1_10.ogg", "halo_reach/dialog/combat/bugger/thrwn/h3_1_8.ogg",
			"halo_reach/dialog/combat/bugger/thrwn/h3_1_8.ogg", "halo_reach/dialog/combat/bugger/thrwn/h3_2_7.ogg",
			"halo_reach/dialog/combat/bugger/thrwn/h3_3_17.ogg", "halo_reach/dialog/combat/bugger/thrwn/h3_3_28.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/bugger/fall/h3_1_11.ogg", "halo_reach/dialog/combat/bugger/fall/h3_1_12.ogg", 
			"halo_reach/dialog/combat/bugger/fall/h3_1_12.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/bugger/pain/h3_1_3.ogg", "halo_reach/dialog/combat/bugger/pain/h3_2_11.ogg",
			"halo_reach/dialog/combat/bugger/pain/h3_2_43.ogg", "halo_reach/dialog/combat/bugger/pain/h3_3_16.ogg",
			"halo_reach/dialog/combat/bugger/pain/h3_3_27.ogg", "halo_reach/dialog/combat/bugger/pain/h3_3_42.ogg",
			"halo_reach/dialog/combat/bugger/pain/h3_4_26.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/bugger/pain_mjr/h3_1_16.ogg", "halo_reach/dialog/combat/bugger/pain_mjr/h3_1_17.ogg",
			"halo_reach/dialog/combat/bugger/pain_mjr/h3_2_21.ogg", "halo_reach/dialog/combat/bugger/pain_mjr/h3_2_42.ogg",
			"halo_reach/dialog/combat/bugger/pain_mjr/h3_4_12.ogg", "halo_reach/dialog/combat/bugger/pain_mjr/h3_4_9.ogg" },
["OnStep"] = { "halo_reach/characters/bugger/long_move/long_move1.ogg", "halo_reach/characters/bugger/long_move/long_move2.ogg",
			"halo_reach/characters/bugger/long_move/long_move3.ogg", "halo_reach/characters/bugger/long_move/long_move4.ogg",
			"halo_reach/characters/bugger/long_move/long_move4.ogg", "halo_reach/characters/bugger/long_move/long_move6.ogg",
			"halo_reach/characters/bugger/long_move/long_move7.ogg", "halo_reach/characters/bugger/long_move/long_move8.ogg",
			"halo_reach/characters/bugger/long_move/long_move9.ogg" },
["OnGib"] = { "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium1.ogg", "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium10.ogg",
			"halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium11.ogg", "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium12.ogg",
			"halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium13.ogg", "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium14.ogg",
			"halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium15.ogg", "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium2.ogg",
			"halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium4.ogg", "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium5.ogg",
			"halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium6.ogg", "halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium7.ogg",
			"halo_reach/characters/flood/combatform_limb_destroyed/floodfleshdestroyed_medium9.ogg" },
["OnPerch"] = { "halo_reach/characters/bugger/bugger_stick/stick1.ogg", "halo_reach/characters/bugger/bugger_stick/stick2.ogg",
			"halo_reach/characters/bugger/bugger_stick/stick3.ogg", "halo_reach/characters/bugger/bugger_stick/stick5.ogg" },
["OnFly"] = { "halo_reach/characters/bugger/flying/flying1.ogg", "halo_reach/characters/bugger/flying/flying2.ogg",
			"halo_reach/characters/bugger/flying/flying3.ogg", "halo_reach/characters/bugger/flying/flying5.ogg",
			"halo_reach/characters/bugger/flying/flying6.ogg", "halo_reach/characters/bugger/flying/flying7.ogg",
			"halo_reach/characters/bugger/flying/flying8.ogg", "halo_reach/characters/bugger/flying/flying9.ogg",
			"halo_reach/characters/bugger/flying/flying10.ogg", "halo_reach/characters/bugger/flying/flying11.ogg",
			"halo_reach/characters/bugger/flying/flying12.ogg", "halo_reach/characters/bugger/flying/flying13.ogg",
			"halo_reach/characters/bugger/flying/flying14.ogg", "halo_reach/characters/bugger/flying/flying15.ogg",
			"halo_reach/characters/bugger/flying/flying16.ogg", "halo_reach/characters/bugger/flying/flying17.ogg" },
	}
} 