AddCSLuaFile()
 
ENT.Voices = {
	["Gúta"] = {
["OnAlert"] = { "halo_reach/dialog/combat/mule/default/none/seefoe/mule1.ogg", "halo_reach/dialog/combat/mule/default/none/seefoe/mule10.ogg",
			"halo_reach/dialog/combat/mule/default/none/seefoe/mule2.ogg", "halo_reach/dialog/combat/mule/default/none/seefoe/mule3.ogg",
			"halo_reach/dialog/combat/mule/default/none/seefoe/mule4.ogg", "halo_reach/dialog/combat/mule/default/none/seefoe/mule5.ogg",
			"halo_reach/dialog/combat/mule/default/none/seefoe/mule7.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/mule/default/none/invsgt/mule50.ogg", "halo_reach/dialog/combat/mule/default/none/invsgt/mule53.ogg",
			"halo_reach/dialog/combat/mule/default/none/invsgt/mule54.ogg", "halo_reach/dialog/combat/mule/default/none/invsgt/mule55.ogg",
			"halo_reach/dialog/combat/mule/default/none/invsgt/mule56.ogg", "halo_reach/dialog/combat/mule/default/none/invsgt/mule6.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/mule/default/none/lst_cntct/mule26.ogg", "halo_reach/dialog/combat/mule/default/none/lst_cntct/mule27.ogg",
			"halo_reach/dialog/combat/mule/default/none/lst_cntct/mule39.ogg", "halo_reach/dialog/combat/mule/default/none/lst_cntct/mule43.ogg",
			"halo_reach/dialog/combat/mule/default/none/lst_cntct/mule48.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/mule/default/none/foundfoe/mule1.ogg", "halo_reach/dialog/combat/mule/default/none/foundfoe/mule10.ogg",
			"halo_reach/dialog/combat/mule/default/none/foundfoe/mule2.ogg", "halo_reach/dialog/combat/mule/default/none/foundfoe/mule3.ogg",
			"halo_reach/dialog/combat/mule/default/none/foundfoe/mule4.ogg", "halo_reach/dialog/combat/mule/default/none/foundfoe/mule5.ogg", 
			"halo_reach/dialog/combat/mule/default/none/foundfoe/mule7.ogg" },
["OnBerserk"] = { "halo_reach/dialog/combat/mule/default/none/brsrk/mule22.ogg", "halo_reach/dialog/combat/mule/default/none/brsrk/mule23.ogg",
			"halo_reach/dialog/combat/mule/default/none/brsrk/mule24.ogg", "halo_reach/dialog/combat/mule/default/none/brsrk/mule9.ogg" },
["OnCharge"] = { "halo_reach/dialog/combat/mule/default/none/charge/mule100.ogg", "halo_reach/dialog/combat/mule/default/none/charge/mule101.ogg",
			"halo_reach/dialog/combat/mule/default/none/charge/mule102.ogg", "halo_reach/dialog/combat/mule/default/none/charge/mule108.ogg",
			"halo_reach/dialog/combat/mule/default/none/charge/mule109.ogg", "halo_reach/dialog/combat/mule/default/none/charge/mule110.ogg",
			"halo_reach/dialog/combat/mule/default/none/charge/mule112.ogg", "halo_reach/dialog/combat/mule/default/none/charge/mule131.ogg",
			"halo_reach/dialog/combat/mule/default/none/charge/mule18.ogg", "halo_reach/dialog/combat/mule/default/none/charge/mule32.ogg" },
["OnRoar"] = { "halo_reach/dialog/combat/mule/default/animation_specific/anger/combat_roar_var1_1.ogg", "halo_reach/dialog/combat/mule/default/animation_specific/anger/combat_roar_var1_2.ogg" },
["OnRoarShort"] = { "halo_reach/dialog/combat/mule/default/animation_specific/sigh/combat_shortroar1.ogg", "halo_reach/dialog/combat/mule/default/animation_specific/sigh/combat_shortroar2.ogg",
			"halo_reach/dialog/combat/mule/default/animation_specific/sigh/combat_shortroar3.ogg", "halo_reach/dialog/combat/mule/default/animation_specific/sigh/combat_shortroar4.ogg",
			"halo_reach/dialog/combat/mule/default/animation_specific/sigh/combat_shortroar5.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/mule/default/none/lift/mule114.ogg", "halo_reach/dialog/combat/mule/default/none/lift/mule115.ogg",
			"halo_reach/dialog/combat/mule/default/none/lift/mule116.ogg", "halo_reach/dialog/combat/mule/default/none/lift/mule117.ogg",
			"halo_reach/dialog/combat/mule/default/none/lift/mule118.ogg", "halo_reach/dialog/combat/mule/default/none/lift/mule119.ogg" },
["OnMeleeStrike"] = { "halo_reach/dialog/combat/mule/default/none/strk/mule59.ogg", "halo_reach/dialog/combat/mule/default/none/strk/mule60.ogg",
			"halo_reach/dialog/combat/mule/default/none/strk/mule61.ogg", "halo_reach/dialog/combat/mule/default/none/strk/mule62.ogg",
			"halo_reach/dialog/combat/mule/default/none/strk/mule63.ogg", "halo_reach/dialog/combat/mule/default/none/strk/mule64.ogg",
			"halo_reach/dialog/combat/mule/default/none/strk/mule65.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/mule/default/none/strk/mule59.ogg", "halo_reach/dialog/combat/mule/default/none/lift/mule115.ogg",
			"halo_reach/dialog/combat/mule/default/none/lift/mule116.ogg", "halo_reach/dialog/combat/mule/default/none/lift/mule117.ogg",
			"halo_reach/dialog/combat/mule/default/none/lift/mule118.ogg", "halo_reach/dialog/combat/mule/default/none/lift/mule119.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/mule/default/none/thrtn/mule30.ogg", "halo_reach/dialog/combat/mule/default/none/thrtn/mule31.ogg",
			"halo_reach/dialog/combat/mule/default/none/thrtn/mule33.ogg", "halo_reach/dialog/combat/mule/default/none/thrtn/mule34.ogg",
			"halo_reach/dialog/combat/mule/default/none/thrtn/mule35.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/mule/default/none/dodge/mule114.ogg", "halo_reach/dialog/combat/mule/default/none/dodge/mule115.ogg",
			"halo_reach/dialog/combat/mule/default/none/dodge/mule116.ogg", "halo_reach/dialog/combat/mule/default/none/dodge/mule117.ogg",
			"halo_reach/dialog/combat/mule/default/none/dodge/mule118.ogg", "halo_reach/dialog/combat/mule/default/none/dodge/mule119.ogg",
			"halo_reach/dialog/combat/mule/default/none/dodge/mule20.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/mule/default/none/dth/mule46.ogg", "halo_reach/dialog/combat/mule/default/none/dth/mule49.ogg",
			"halo_reach/dialog/combat/mule/default/none/dth/mule52.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/mule/default/none/dth_mjr/mule46.ogg", "halo_reach/dialog/combat/mule/default/none/dth_mjr/mule49.ogg",
			"halo_reach/dialog/combat/mule/default/none/dth_mjr/mule52.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/mule/default/none/dth_fall/mule46.ogg", "halo_reach/dialog/combat/mule/default/none/dth_fall/mule49.ogg",
			"halo_reach/dialog/combat/mule/default/none/dth_fall/mule52.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/mule/default/none/thrwn/mule144.ogg", "halo_reach/dialog/combat/mule/default/none/thrwn/mule40.ogg",
			"halo_reach/dialog/combat/mule/default/none/thrwn/mule41.ogg", "halo_reach/dialog/combat/mule/default/none/thrwn/mule42.ogg",
			"halo_reach/dialog/combat/mule/default/none/thrwn/mule46.ogg", "halo_reach/dialog/combat/mule/default/none/thrwn/mule49.ogg",
			"halo_reach/dialog/combat/mule/default/none/thrwn/mule51.ogg", "halo_reach/dialog/combat/mule/default/none/thrwn/mule52.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/mule/default/none/fall/mule46.ogg", "halo_reach/dialog/combat/mule/default/none/fall/mule49.ogg",
			"halo_reach/dialog/combat/mule/default/none/fall/mule52.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/mule/default/none/pain/mule103.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule104.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain/mule105.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule106.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain/mule107.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule111.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain/mule113.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule146.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain/mule45.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule47.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain/mule96.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule97.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain/mule98.ogg", "halo_reach/dialog/combat/mule/default/none/pain/mule99.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/mule/default/none/pain_mjr/mule85.ogg", "halo_reach/dialog/combat/mule/default/none/pain_mjr/mule86.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain_mjr/mule87.ogg", "halo_reach/dialog/combat/mule/default/none/pain_mjr/mule88.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain_mjr/mule89.ogg", "halo_reach/dialog/combat/mule/default/none/pain_mjr/mule90.ogg",
			"halo_reach/dialog/combat/mule/default/none/pain_mjr/mule91.ogg" },
["OnMoveFoley"] = { "halo_reach/characters/mule/mule_shortmove/mule_shortmove1.ogg", "halo_reach/characters/mule/mule_shortmove/mule_shortmove2.ogg",
			"halo_reach/characters/mule/mule_shortmove/mule_shortmove3.ogg", "halo_reach/characters/mule/mule_shortmove/mule_shortmove4.ogg",
			"halo_reach/characters/mule/mule_shortmove/mule_shortmove5.ogg", "halo_reach/characters/mule/mule_shortmove/mule_shortmove6.ogg" },
["OnStep"] = { "halo_reach/characters/mule/mule_feet/mule_foot1.ogg", "halo_reach/characters/mule/mule_feet/mule_foot2.ogg",
			"halo_reach/characters/mule/mule_feet/mule_foot3.ogg", "halo_reach/characters/mule/mule_feet/mule_foot4.ogg",
			"halo_reach/characters/mule/mule_feet/mule_foot5.ogg", "halo_reach/characters/mule/mule_feet/mule_foot6.ogg",
			"halo_reach/characters/mule/mule_feet/mule_foot7.ogg" },
["SFXOnMelee"] = { "halo_reach/characters/hunter/hunter_arm_melee/hunter_arm_melee1.ogg", "halo_reach/characters/hunter/hunter_arm_melee/hunter_arm_melee2.ogg",
			"halo_reach/characters/hunter/hunter_arm_melee/hunter_arm_melee3.ogg" },
["SFXOnMeleeImpact"] = { "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage1.ogg", "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage2.ogg",
			"halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage3.ogg", "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage4.ogg",
			"halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage5.ogg", "halo_reach/characters/hunter/hunter_hit_damage/hunter_hit_damage6.ogg" }
	}
}