AddCSLuaFile()

ENT.Voices = {
	["Trooper1"] = {
["OnLook"] = { "halo_reach/dialog/combat/trooper1/default/03_postcombat/look/look_1.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/look/look_2.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/look/look_3.ogg" },
["OnStare"] = { "halo_reach/dialog/combat/trooper1/default/03_postcombat/look_lngtme/look_lngtme_1.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/look_lngtme/look_lngtme_10.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/look_lngtme/look_lngtme_14.ogg",
			"halo_reach/dialog/combat/trooper1/default/03_postcombat/look_lngtme/look_lngtme_15.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/look_lngtme/look_lngtme_7.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/look_lngtme/look_lngtme_8.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/trooper1/default/01_contact/seefoe/seefoe_1.ogg", "halo_reach/dialog/combat/trooper1/default/01_contact/seefoe/seefoe_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/01_contact/seefoe/seefoe_3.ogg", "halo_reach/dialog/combat/trooper1/default/01_contact/seefoe/seefoe_4.ogg" },
["OnAlertMoreFoes"] = { "halo_reach/dialog/combat/trooper1/default/01_contact/morefoe/morefoe_1.ogg", "halo_reach/dialog/combat/trooper1/default/01_contact/morefoe/morefoe_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/01_contact/morefoe/morefoe_3.ogg", "halo_reach/dialog/combat/trooper1/default/01_contact/morefoe/morefoe_4.ogg"},
["OnInvestigate"] = { "halo_reach/dialog/combat/trooper1/default/05_search/invsgt/invsgt_1.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/invsgt/invsgt_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/05_search/invsgt/invsgt_3.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/invsgt/invsgt_4.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/invsgt/invsgt_6.ogg" },
["OnInvestigateFail"] = { "halo_reach/dialog/combat/trooper1/default/05_search/invsgt_fail/invsgt_fail_1.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/invsgt_fail/invsgt_fail_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/05_search/invsgt_fail/invsgt_fail_3.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/invsgt_fail/invsgt_fail_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/05_search/invsgt_fail/invsgt_fail_5.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/trooper1/default/05_search/lst_cntct/lst_cntct_1.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/lst_cntct/lst_cntct_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/05_search/lst_cntct/lst_cntct_3.ogg", "halo_reach/dialog/combat/trooper1/default/05_search/lst_cntct/lst_cntct_4.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_10.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_11.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_5.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_7.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_8.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/shoot/shoot_9.ogg" },
["OnCharge"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/charge/charge_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/charge/charge_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/charge/charge_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/charge/charge_4.ogg" },
["OnDamagedFoe"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_10.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_11.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_12.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_4.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_8.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/damaged_enemy/damaged_enemy_9.ogg" },
["OnKillAlly"] = { "halo_reach/dialog/combat/trooper1/default/10_exclaim/scld_plr_kllally/scld_plr_kllally_2.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/scld_plr_kllally/scld_plr_kllally_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/scld_plr_kllally/scld_plr_kllally_4.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/scld_plr_kllally/scld_plr_kllally_5.ogg" },
["OnBetrayal"] = { "halo_reach/dialog/combat/trooper1/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr_1.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr_3.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr_5.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/betray/betray_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/betray/betray_5.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/betray/betray_6.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/betray/betray_7.ogg" },
["OnForgive"] = { "halo_reach/dialog/combat/trooper1/default/10_exclaim/forgive/forgive_2.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/forgive/forgive_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/forgive/forgive_4.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/forgive/forgive_5.ogg" },
["OnCover"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/pinned/pinned_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/pinned/pinned_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/pinned/pinned_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/pinned/pinned_4.ogg" },
["OnReload"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/reloading/reloading_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/reloading/reloading_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/reloading/reloading_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/reloading/reloading_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/reloading/reloading_5.ogg" },
["OnGrenadeThrow"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_10.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_11.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_13.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_8.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/strk_grnd/strk_grnd_9.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/thrtn/thrtn_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/thrtn/thrtn_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/thrtn/thrtn_5.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/thrtn/thrtn_6.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/trooper1/default/03_postcombat/chkfoebdy/chkfoebdy_1.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/chkfoebdy/chkfoebdy_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/03_postcombat/chkfoebdy/chkfoebdy_5.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/chkfoebdy/chkfoebdy_6.ogg" },
["OnShootCorpse"] = { "halo_reach/dialog/combat/trooper1/default/03_postcombat/shotfoebdy/shotfoebdy_11.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/shotfoebdy/shotfoebdy_15.ogg",
			"halo_reach/dialog/combat/trooper1/default/03_postcombat/shotfoebdy/shotfoebdy_4.ogg", "halo_reach/dialog/combat/trooper1/default/03_postcombat/shotfoebdy/shotfoebdy_5.ogg",
			"halo_reach/dialog/combat/trooper1/default/03_postcombat/shotfoebdy/shotfoebdy_8.ogg" },
["OnKillPlayer"] = { "halo_reach/dialog/combat/trooper1/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr_1.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr_3.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr_4.ogg" },
["OnPanic"] = { "halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_11.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_12.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_3.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_5.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_7.ogg", "halo_reach/dialog/combat/trooper1/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_8.ogg" },
["OnUnderAttack"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_5.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/undr_fire/undr_fire_8.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/warn_incmn/warn_incmn_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/warn_incmn/warn_incmn_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/warn_incmn/warn_incmn_3.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/warn_incmn/warn_incmn_4.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_1.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_10.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_2.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_4.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_5.ogg",
			"halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_8.ogg", "halo_reach/dialog/combat/trooper1/default/02_combat/melee_attack/melee_attack_9.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/dive/dive_4.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dive/dive_5.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dive/dive_6.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dive/dive_7.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dive/dive_8.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/dodge/dodge_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dodge/dodge_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dodge/dodge_6.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dodge/dodge_9.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_11.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_12.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_13.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_2.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_5.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth/dth_7.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_3.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_5.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_7.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_8.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_mjr/dth_mjr_9.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_3.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_5.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_7.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/dth_fall/dth_fall_8.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_3.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_5.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/thrwn/thrwn_7.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/fall/fall_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/fall/fall_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/fall/fall_4.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/fall/fall_5.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/fall/fall_7.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_1.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_10.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_11.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_13.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_2.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_5.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_7.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_8.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain/pain_9.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_11.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_13.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_14.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_4.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_5.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_6.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/pain_mjr/pain_mjr_7.ogg" },
["OnStep"] = { "halo_reach/characters/marines/marine_shortmove/shortmove1.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove10.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove11.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove12.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove13.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove14.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove15.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove16.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove17.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove18.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove19.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove2.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove20.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove21.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove22.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove23.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove24.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove25.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove26.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove27.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove28.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove29.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove3.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove30.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove31.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove32.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove4.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove5.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove6.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove7.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove8.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove9.ogg" },
["OnLand"] = { "halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_14.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_15.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_2.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_3.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_4.ogg", "halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_7.ogg",
			"halo_reach/dialog/combat/trooper1/default/11_involuntary/lift/lift_8.ogg" },
["OnTrade"] = { "halo_reach/dialog/combat/trooper1/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn_1.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn_3.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn_4.ogg",
			"halo_reach/dialog/combat/trooper1/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn_5.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn_6.ogg",
			"halo_reach/dialog/combat/trooper1/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn_1.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn_2.ogg",
			"halo_reach/dialog/combat/trooper1/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn_4.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn_5.ogg",
			"halo_reach/dialog/combat/trooper1/default/07_respond/thnk/thnk_1.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/thnk/thnk_2.ogg", "halo_reach/dialog/combat/trooper1/default/07_respond/thnk/thnk_3.ogg" }
	}, 
	["Trooper3"] = {
["OnLook"] = { "halo_reach/dialog/combat/trooper3/default/03_postcombat/look/look12.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/look/look6.ogg" },
["OnStare"] = { "halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme1.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme10.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme13.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme14.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme15.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme17.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme19.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/look_lngtme/look_lngtme21.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/trooper3/default/01_contact/seefoe/seefoe1.ogg", "halo_reach/dialog/combat/trooper3/default/01_contact/seefoe/seefoe2.ogg",
			"halo_reach/dialog/combat/trooper3/default/01_contact/seefoe/seefoe3.ogg", "halo_reach/dialog/combat/trooper3/default/01_contact/seefoe/seefoe4.ogg" },
["OnAlertMoreFoes"] = { "halo_reach/dialog/combat/trooper3/default/01_contact/morefoe/morefoe1.ogg", "halo_reach/dialog/combat/trooper3/default/01_contact/morefoe/morefoe2.ogg",
			"halo_reach/dialog/combat/trooper3/default/01_contact/morefoe/morefoe3.ogg", "halo_reach/dialog/combat/trooper3/default/01_contact/morefoe/morefoe4.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/trooper3/default/05_search/invsgt/invsgt1.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/invsgt/invsgt2.ogg",
			"halo_reach/dialog/combat/trooper3/default/05_search/invsgt/invsgt3.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/invsgt/invsgt4.ogg",
			"halo_reach/dialog/combat/trooper3/default/05_search/invsgt/invsgt5.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/invsgt/invsgt6.ogg" },
["OnInvestigateFail"] = { "halo_reach/dialog/combat/trooper3/default/05_search/invsgt_fail/invsgt_fail1.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/invsgt_fail/invsgt_fail2.ogg",
			"halo_reach/dialog/combat/trooper3/default/05_search/invsgt_fail/invsgt_fail3.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/invsgt_fail/invsgt_fail4.ogg",
			"halo_reach/dialog/combat/trooper3/default/05_search/invsgt_fail/invsgt_fail5.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/trooper3/default/05_search/lst_cntct/lst_cntct1.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/lst_cntct/lst_cntct2.ogg", "halo_reach/dialog/combat/trooper3/default/05_search/lst_cntct/lst_cntct3.ogg",
			"halo_reach/dialog/combat/trooper3/default/05_search/lst_cntct/lst_cntct4.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/shoot/shoot1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/shoot/shoot10.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/shoot/shoot2.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/shoot/shoot3.ogg" },
["OnCharge"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/charge/charge1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/charge/charge2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/charge/charge3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/charge/charge4.ogg" },
["OnDamagedFoe"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/damaged_enemy/damaged_enemy1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/damaged_enemy/damaged_enemy12.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/damaged_enemy/damaged_enemy13.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/damaged_enemy/damaged_enemy2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/damaged_enemy/damaged_enemy3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/damaged_enemy/damaged_enemy6.ogg" },
["OnKillAlly"] = { "halo_reach/dialog/combat/trooper3/default/10_exclaim/scld_plr_kllally/scld_plr_kllally1.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/scld_plr_kllally/scld_plr_kllally2.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/scld_plr_kllally/scld_plr_kllally3.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/scld_plr_kllally/scld_plr_kllally4.ogg" },
["OnBetrayal"] = { "halo_reach/dialog/combat/trooper3/default/10_exclaim/betray/betray1.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/betray/betray2.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/betray/betray3.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/betray/betray4.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/betray/betray5.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/betray/betray6.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr1.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr2.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr3.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr4.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr5.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/shoot_betrayed_plr/shoot_betrayed_plr6.ogg" },
["OnForgive"] = { "halo_reach/dialog/combat/trooper3/default/10_exclaim/forgive/forgive3.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/forgive/forgive4.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/forgive/forgive5.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/forgive/forgive6.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/forgive/forgive7.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/forgive/forgive8.ogg" },
["OnShootCorpse"] = { "halo_reach/dialog/combat/trooper3/default/03_postcombat/shotfoebdy/shotfoebdy2.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/shotfoebdy/shotfoebdy3.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/shotfoebdy/shotfoebdy4.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/shotfoebdy/shotfoebdy5.ogg" },
["OnKillPlayer"] = { "halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr1.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr11.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr12.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr14.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr2.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr4.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr5.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/kill_betrayed_plr/kill_betrayed_plr9.ogg" },
["OnCover"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/pinned/pinned1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/pinned/pinned2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/pinned/pinned3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/pinned/pinned4.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/pinned/pinned5.ogg" },
["OnReload"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/reloading/reloading1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/reloading/reloading2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/reloading/reloading3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/reloading/reloading4.ogg" },
["OnGrenadeThrow"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd10.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd11.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd4.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd5.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd6.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd7.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd8.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/strk_grnd/strk_grnd9.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn10.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn4.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn5.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn6.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/thrtn/thrtn7.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/trooper3/default/03_postcombat/look/look12.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/look/look6.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/chkfoebdy/chkfoebdy1.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/chkfoebdy/chkfoebdy2.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/chkfoebdy/chkfoebdy3.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/chkfoebdy/chkfoebdy5.ogg",
			"halo_reach/dialog/combat/trooper3/default/03_postcombat/chkfoebdy/chkfoebdy6.ogg", "halo_reach/dialog/combat/trooper3/default/03_postcombat/chkfoebdy/chkfoebdy7.ogg" },
["OnPanic"] = { "halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd1.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd10.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd11.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd2.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd3.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd4.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd6.ogg", "halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd7.ogg",
			"halo_reach/dialog/combat/trooper3/default/10_exclaim/panic_plsmgrnd/panic_plsmgrnd8.ogg" },
["OnUnderAttack"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire4.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire5.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire6.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/undr_fire/undr_fire7.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/warn_incmn/warn_incmn1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/warn_incmn/warn_incmn2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/warn_incmn/warn_incmn3.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/warn_incmn/warn_incmn4.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/warn_incmn/warn_incmn5.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/warn_incmn/warn_incmn6.ogg" },
["OnMelee"] = { "halo_reach/dialog/combat/trooper3/default/02_combat/melee_attack/melee_attack1.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/melee_attack/melee_attack2.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/melee_attack/melee_attack4.ogg", "halo_reach/dialog/combat/trooper3/default/02_combat/melee_attack/melee_attack6.ogg",
			"halo_reach/dialog/combat/trooper3/default/02_combat/melee_attack/melee_attack7.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive2.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive3.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive4.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive5.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive7.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dive/dive8.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/dodge/dodge1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dodge/dodge2.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dodge/dodge3.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dodge/dodge4.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dodge/dodge5.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth10.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth11.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth12.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth13.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth2.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth3.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth4.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth5.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth6.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth8.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth/dth9.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr10.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr11.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr12.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr14.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr17.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr18.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr2.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr3.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr4.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr5.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr6.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr7.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr8.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_mjr/dth_mjr9.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall10.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall2.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall3.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall4.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall6.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall7.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall8.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/dth_fall/dth_fall9.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn10.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn2.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn3.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn4.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn5.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn6.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn7.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn8.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/thrwn/thrwn9.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/fall/fall1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/fall/fall2.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/fall/fall4.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/fall/fall5.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/fall/fall6.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/fall/fall7.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain10.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain11.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain12.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain13.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain14.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain15.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain16.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain17.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain18.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain19.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain20.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain21.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain23.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain24.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain25.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain26.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain27.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain28.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain8.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain/pain9.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr1.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr10.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr11.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr12.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr13.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr14.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr15.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr16.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr18.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr19.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr2.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr20.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr21.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr22.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr23.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr24.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr25.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr26.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr27.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr28.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr29.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr3.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr4.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr5.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr6.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr7.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/pain_mjr/pain_mjr9.ogg" },
["OnStep"] = { "halo_reach/characters/marines/marine_shortmove/shortmove1.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove10.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove11.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove12.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove13.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove14.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove15.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove16.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove17.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove18.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove19.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove2.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove20.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove21.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove22.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove23.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove24.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove25.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove26.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove27.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove28.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove29.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove3.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove30.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove31.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove32.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove4.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove5.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove6.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove7.ogg",
			"halo_reach/characters/marines/marine_shortmove/shortmove8.ogg", "halo_reach/characters/marines/marine_shortmove/shortmove9.ogg" },
["OnLand"] = { "halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift10.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift11.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift2.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift3.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift5.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift6.ogg",
			"halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift7.ogg", "halo_reach/dialog/combat/trooper3/default/11_involuntary/lift/lift9.ogg" },
["OnTrade"] = { "halo_reach/dialog/combat/trooper3/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn1.ogg", "halo_reach/dialog/combat/trooper3/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn2.ogg",
			"halo_reach/dialog/combat/trooper3/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn3.ogg", "halo_reach/dialog/combat/trooper3/default/07_respond/ok_plr_trdwpn/ok_plr_trdwpn4.ogg",
			"halo_reach/dialog/combat/trooper3/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn1.ogg", "halo_reach/dialog/combat/trooper3/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn2.ogg",
			"halo_reach/dialog/combat/trooper3/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn3.ogg", "halo_reach/dialog/combat/trooper3/default/07_respond/scrn_plr_wrswpn/scrn_plr_wrswpn8.ogg",
			"halo_reach/dialog/combat/trooper3/default/07_respond/thnk/thnk1.ogg", "halo_reach/dialog/combat/trooper3/default/07_respond/thnk/thnk2.ogg",
			"halo_reach/dialog/combat/trooper3/default/07_respond/thnk/thnk3.ogg", "halo_reach/dialog/combat/trooper3/default/07_respond/thnk/thnk5.ogg" },
	}
}